### ISSUE TITLE
Créer un logo ou icone pour le mmmfest

### ISSUE THREAD

**Issue by SebLemoine** [assemblee-virtuelle/mmmfest#11]
Pour remplacer celui des GV !

**Comment by GuillaumeAV** [comment]
Une idée comme ça : 

Prendre la typo des Grands Voisins + la forme courbe du logo des Grands Voisins, et remplacer par MMM Fest :-)

Ce serait pas mal et simple non ? D'autres idées ? Des gens motivés ?
