### ISSUE TITLE
Documents et types de document : Résoudre le bug et faire évoluer

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#15]
Résoudre le bug

Créer un petit thésaurus ...

**Comment by GuillaumeAV** [comment]
Enlever par ailleurs type de document de l'interface admin des utilisateurs : 

Je pense que outre les sites web, et pages à propos de,  on va gérer des documents de type : 

- CodeSocial
- Notes
- Présentation

**Comment by SebLemoine** [comment]
On peut laisser la possibilité a des super admin de créer des documenttype ? Ce qui permettra une meilleur "flexibilité" des types de document.
Qu'en pense tu @GuillaumeAV ?

**Comment by GuillaumeAV** [comment]
Oui voila !!!

**Comment by GuillaumeAV** [comment]
Yop ! C'est trop cool je me suis amusé à créer des docs et des types de documents :-) Par contre les types de documents n'apparaissent pas dans le menu quand on crée un document ... il doit manquer un petit rouage ?

**Comment by SebLemoine** [comment]
C'est résolu ! je suis allé trop vite sur l'issue qui avait pour but de retirer certain résultat dans la partie publique
