### ISSUE TITLE
Assemblée Virtuelle n'est pas référencée dans les orgas lors du processus d'inscription ..

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#19]
J'imagine que tu l'as identifié ...

**Comment by SebLemoine** [comment]
@GuillaumeAV Elle est référencée ! Mais sous le nom de AV_test :D Je modifierai le nom de l'association :)
Je prend le nom de la base de donnée sql, par sur semForms, pour un gain de performance.
