### ISSUE TITLE
Changer les textes de la plateforme MMM

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#20]

**Comment by GuillaumeAV** [comment]
[Ici le lien](https://docs.google.com/document/d/1AIRMDB378LedNzS5jip7zOzBfREBqB7MpvmkBHLcU3I/edit?usp=sharing) vers les textes suivants : 

[Bannière] Page Code Social
[Bannière] Page Programme
[Bannière] Page Inscriptions
[Bannière] Page Infos pratiques

Texte mail de confirmation de création de compte - Participants
Texte mail de confirmation de création de compte - Référents structures

Texte formulaire personne
Texte formulaire Orga
Texte formulaire Projet
Texte formulaire Événement
Texte formulaire Document
Texte formulaire Proposition

**Comment by SebLemoine** [comment]
Normalement ok ! A vérifier

**Comment by GuillaumeAV** [comment]
Génial !
