### ISSUE TITLE
Trouver des images de fond 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#21]
Interface admin : Personne, orga, événement, etc.

**Comment by SebLemoine** [comment]
pareil pour l'onglet connexion ?
Car si c'est bien l'image au dessus présent, effectivement, dans toute la partie admin, on peut faire une banderole rapide avec l'image de l'introduction du site

**Comment by ircocomat** [comment]
je t'ai envoyé des photos via we transfer quand tu as le temps
