### ISSUE TITLE
Améliorer la bannière

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#28]
Il faudrait mettre les liens suivants dans cet ordre : 

Code Social - Programme - Inscriptions - Informations pratiques

J'imagine des pages simples sans fioritures ... Facile ? 

Pour accéder aux textes, [cliquer ici](https://docs.google.com/document/d/1AIRMDB378LedNzS5jip7zOzBfREBqB7MpvmkBHLcU3I/edit?usp=sharing) !

**Comment by SebLemoine** [comment]
Elle est ok la bannière ?
