### ISSUE TITLE
Créer un bandeau en haut de la home

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#3]
"Bienvenue au MMMfest ! - Domaine de Millemont - 4 au 8 octobre 2017"

**Comment by GuillaumeAV** [comment]
Yop ! J'ai fait très rapidement un début de maquette :-) C'est un work in progress sans fioriture que vous pouvez adpater à votre guise !! https://docs.google.com/drawings/d/1IYBfpcPZfEoLkbTu7sxyEmXW49dOWaIiaqfvvB_IZk4/edit?usp=sharing

**Comment by SebLemoine** [comment]
Salut @GuillaumeAV !
La maquette que tu as faite doit remplacer l'animation des GV ? Je peux faire une sorte de page d'accueil avec l'image et le texte et de, grave a un bouton, accéder la partie carto.
Le texte que tu as mis sera toujours disponible une fois passé sur la carto grâce à l'espace attribué pour les "annonces" à côté des résultats d'une requête.

**Comment by GuillaumeAV** [comment]
@SebLemoine je le voyais davantage comme un ajout sur homepage ... Pas d'animation de début (plus simple) Je l'ai customisé un poil plus la .. Mais en fait on dit peut être la même chose ?

**Comment by SebLemoine** [comment]
On dit la même chose :) je préférais être sûr :) 
J'ai ma confirmation :)
