### ISSUE TITLE
Ajouter hasInterest (Label Domaine thématique) et hasSubject (Label Mots-clés)

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#37]
- Ajouter hasInterest (Label Domaine thématique) sur les classes Orga et Proposition
- Ajouter hasSubject (Label Mots-clés) sur les classes Personne, 

Par ailleurs, bien veiller à ce que Domaine(s) thématique(s) et Mots-clés (uri : hasSubject) apparaissent dans cet ordre, juste après les datatypes properties (email, tel, etc.).

**Comment by SebLemoine** [comment]
Il manque hasSubject pour Personne :/ J'ai oublié de le rajouter
Je m'en occupe tout de suite !
