### ISSUE TITLE
Changer les labels des formulaires ...

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#4]
[Ici le lien](https://docs.google.com/document/d/1ZDl-f-s9vthg-D_XB3nsoPDJ2rO8YCfidXsJZExh7hA/edit?usp=sharing) vers les suggestions de modification.

Seb, je peux les mettre directement dans l'ontologie via protege, ou te faire un tableur avec les URI et les modifs de labels correspondants ... Qu'est ce qui t'arrangerait le plus ?

**Comment by SebLemoine** [comment]
Pour le formulaire de personne, il n'y a pas le champ homePage, il n'y avais que le champ aboutPage. Je rajoute la champ ?

**Comment by SebLemoine** [comment]
Pour organisation, je n'ai pas supprimé le champ comment car il me "sert" à l'heure actuel comme description courte de l'organisation (dans les résultats de recherche, petite description en dessous de chaque organisation) , si vous avez d'autre proposition ?
J'ai également gardé le champ hostedIn pour la géolocalisation car je ne sais pas quoi géolocaliser à l'heure actuel :D

**Comment by SebLemoine** [comment]
Pour projet, j'ai gardé comment pour la même raison que organisation,
Je rajouterai les champs "offers" et "hasInterest" plus tard car cela implique d’arrêter semanticForms et de changer les specs de forms. 
J'ai gardé image pour le moment tel quel qui sera modifié par la même procédure que orga et personne

**Comment by SebLemoine** [comment]
Pour event, la géolocalisation est presque faite, il faut que je modifie le tout pour que cela fonctionne
Les nouveau champs, je le ferai en même temps que les autres champs
D'ailleurs, les champs a pour participant et a pour organisateur existe déjà

**Comment by SebLemoine** [comment]
Pour proposition, je doit rajouter le champs hasInterest

**Comment by SebLemoine** [comment]
Recap :
- pour personne
ajouter le champ homePage
- pour orga
retirer le champ hostedIn
- pour projet
ajouter le champ offers et hasInterrest
modifier procédure pour l'image
- pour event
géolocalisation
modifier procédure pour l'image
Ajouter Étage
Ajouter pièce
Ajouter heure début
Ajouter heure fin
- pour proposition
ajouter le champ hasInterest

**Comment by SebLemoine** [comment]
@GuillaumeAV normalement, j'ai placé l’ensemble des labels !

**Comment by GuillaumeAV** [comment]
Quelques dernières modifs sur les labels et formulaires ici : https://docs.google.com/document/d/1ZDl-f-s9vthg-D_XB3nsoPDJ2rO8YCfidXsJZExh7hA/edit?usp=sharing

**Comment by GuillaumeAV** [comment]
Ontologie mise à jour dans protegé, avec quelques modifs de labels pour ca corresponde à ceux proposés dans le doc ci-dessus ...

**Comment by GuillaumeAV** [comment]
On est quasi bon !!! 

Dernières modifs à faire : https://docs.google.com/document/d/1ZDl-f-s9vthg-D_XB3nsoPDJ2rO8YCfidXsJZExh7hA/edit?usp=sharing

**Comment by SebLemoine** [comment]
Pout l'autocompmetion des adresses :
https://adresse.data.gouv.fr/api
