### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by ircocomat** [assemblee-virtuelle/mmmfest#42]
Le logo des GV est revenu ... ? 
Peut on le mettre en noir  et blanc ?

**Comment by SebLemoine** [comment]
Problème lié peut être au cache ?

**Comment by ircocomat** [comment]
je ne sais pas ce qu'est le cache,entous les cas lelogodes grands voisins apparait pour moi... excepté quand je clique sur la banniere inscriptions, je suis reconduit sur une nouvelle page avec logo du mmmfest
