### ISSUE TITLE
inscriptions page intermédiaire repas 

### ISSUE THREAD

**Issue by ircocomat** [assemblee-virtuelle/mmmfest#47]
Salut Seb, peux tu ajouter une page intermédiaire lors de l'inscription concernant la participation au repas lors du festival afin de connaitre le nombre de repas qu'il va y avoir . le participant est reconduit vers une page formulaire ou l'on peut télécharger le formulaire suivant : 

https://docs.google.com/document/d/1R_B_3hu3Vrm1joeZB95pcJVBr7H4IT67Nn4OR-8ktG4/edit

Guillaume dis moi ce que tu pense de cette page formulaire ca ma l'air rudimentaire et j'ai la nette impression qu'en cliquant les participants modifierons seulement le excel.... Il est impossible de mettre des cases de cochage avec GoogleSheet

**Comment by SebLemoine** [comment]
@GuillaumeAV @ircocomat, il est peut etre possible de le faire directement sur Google Form ? Comme ca on peut imposer certaine forme de reponse ?

**Comment by GuillaumeAV** [comment]
@seblemoine On peut joindre un gform si ca te parait trop compliqué de coder  le truc dans la plateforme ! Dispo cet après midi ?

**Comment by simonLouvet** [comment]
on peut créer les repas comme des événements (dans la base sémantique) et demander aux personne de se lier aux repas pour lesquels ils seront la ou faciliter les choses par le formulaire d'inscription?

**Comment by SebLemoine** [comment]
Super idée @simonLouvet !

**Comment by ircocomat** [comment]
Je pense aussi après réfléxion que c'est une bonne idée !

**Comment by SebLemoine** [comment]
Ce sera une proposition d’amélioration pour la prochaine édition !
