### ISSUE TITLE
faire en sorte que la recherche par batiment soit possible autrement

### ISSUE THREAD

**Issue by SebLemoine** [assemblee-virtuelle/mmmfest#52]
créer un menu déroulant a côté de thématiques

**Comment by GuillaumeAV** [comment]
Pas sur que ce soit nécessaire Seb ! On a jamais ce genre de besoin sur cartoGV ... Le clic sur les batiments suffit aux gens ... PAr contre ce serait bien de renseigner sur la carto le nom des batiments ...

**Comment by GuillaumeAV** [comment]
Nom et nombre des pièces pour les workshop : 

Bâtiments (pas de photo pour le moment)

Grand Château - RDC - Pièce 1 - 15 personnes 
Grand Château - RDC - Pièce 2 - 15 personnes
Grand Château - RDC - Pièce 3 centrale - 50 personnes
Grand Château - RDC - Pièce 4 - 20 personnes
Grand Château - RDC - Pièce 5 - 10 personnes
Grand Château - RDC - Pièce 6 - 10 personnes

Grand Château - 1er - Pièce 1 - 15 personnes
Grand Château - 1er - Pièce 2 - 15 personnes
Grand Château - 1er - Pièce 3 - 15 personnes
Grand Château - 1er - Pièce 4 - 10 personnes
Grand Château - 1er - Pièce 5 - 15 personnes 
Grand Château - 1er - Pièce 6 - 15 personnes
Grand Château - 1er - Pièce 7 - 15 personnes 
Grand Château - 1er - Pièce 8 - 15 personnes

Cour des cochets - Atelier 1 
Cour des cochets - Atelier 2

**Comment by SebLemoine** [comment]
Je m'en occuperai demain ou vendredi ;)

**Comment by SebLemoine** [comment]
On laisse comme c'est !
