### ISSUE TITLE
Des données intitulées false dans mon formulaire person...

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#58]
Elles ne s'affichent donc pas en front, parmi lesquelles ... 

- Workshop chemins de la transition
- Les banquets gastrosophiques
- Atelier cuisine collective
- Concert de cloture 

Ca vient peut-être de SF ?

**Comment by SebLemoine** [comment]
A voir si c'est résolu avec la solution de repli de l'issue #59
