### ISSUE TITLE
Problèmes de lenteur 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#59]
Le chargement des pages prend un temps anormalement long ;..

**Comment by SebLemoine** [comment]
Il faut redemarrer sf, je m'en occupe

**Comment by GuillaumeAV** [comment]
Au top !

**Comment by GuillaumeAV** [comment]
Il semble par ailleurs que la complétion ait du mal ... Même origine j'imagine ?

**Comment by SebLemoine** [comment]
problème non localisé précisément à l'heure actuel mais solution de repli trouvée en test pour le moment

**Comment by GuillaumeAV** [comment]
Ca va trop vite c'est géniaaaaaal :-)
