### ISSUE TITLE
Enlever l'image de Thibaud qui est présente par défaut quand on crée un projet ;-)

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#61]
Il est beau mais tout de même :-)

**Comment by GuillaumeAV** [comment]
Ah maintenant c'en est une autre ;-) Celle que j'ai voulu mettre pour le workshop carto ;-)

**Comment by SebLemoine** [comment]
je n'ai pas ce problème de mon côté

**Comment by SebLemoine** [comment]
testé IRL
