### ISSUE TITLE
Mettre Prénom + No... sur les vignettes sans image ...

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#68]
Ce serait un gros plus, pas facile de voir quand il n'y a pas les photos, c'est d'autant plus vrai sur smartphone ... 

J'ai mis Prénom + No... pour signifier qu'on pouvait limiter le nombre de caractères à (...?) pour ne pas surcharger les vignettes ...

**Comment by SebLemoine** [comment]
Il serait plus facile pour moi d'avoir une image plus visible !

**Comment by GuillaumeAV** [comment]
Ooh que c'est beau !!! :-)
