### ISSUE TITLE
Avoir une procédure unique pour mettre des images

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/mmmfest#7]
Télécharger plutôt qu'un lien ...

Ce qui suppose au passage, de créer la datatype propertie.. Je m'en occupe ..

**Comment by SebLemoine** [comment]
Pour l'instant, j'ai fais comme pour GV. 
Je ferais cette modif plus tard une fois que tout sera ok.
See commit : 188042652d2529b531745641d7b2e0728224f8ef
